### ISSUE TITLE
Organizar uma estrutura de pastas

### ISSUE THREAD

**Issue by JCDMeira** [BrunoOliveira16/FORMULARIO-INSCRICAO#2]
Organizar a estrutura de pastas para seguir um modelo, isso ajuda a se organizar. Vou te mandar mais detalhes mais específicos no discord

**Comment by BrunoOliveira16** [comment]
Efetuada a organização da estrutura das pastas do projeto conforme modelo orientado. Atualizado arquivos src e readme.
